import {
  Student,
  Teacher,
  TahfizGroup,
  MemorizationRecord,
  User,
  PredicateType,
  Assessment,
} from '@/types/tahfiz';

export function calculateAssessment(
  kelancaran: number,
  tajwid: number,
  makhraj: number,
  ketepatanHafalan: number,
  adab: number
): Assessment {
  const avg = Math.round((kelancaran + tajwid + makhraj + ketepatanHafalan + adab) / 5);
  let predicate: PredicateType = 'Perlu Bimbingan';
  if (avg >= 90) {
    predicate = 'Sangat Baik';
  } else if (avg >= 80) {
    predicate = 'Baik';
  } else if (avg >= 70) {
    predicate = 'Cukup';
  } else {
    predicate = 'Perlu Bimbingan';
  }

  return {
    kelancaran,
    tajwid,
    makhraj,
    ketepatanHafalan,
    adab,
    finalScore: avg,
    predicate,
  };
}

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'tch-1',
    name: 'Ustadz Ahmad Zaki, Lc., Al-Hafizh',
    nip: '198804122014021003',
    gender: 'L',
    phone: '0812-3456-7890',
    email: 'ahmad.zaki@pesantren.id',
    specialty: 'Sanad Qira\'at & Tahfiz 30 Juz',
    totalStudents: 5,
  },
  {
    id: 'tch-2',
    name: 'Ustadzah Fatimah Azzahra, S.Th.I',
    nip: '199208152018032005',
    gender: 'P',
    phone: '0813-9876-5432',
    email: 'fatimah.azzahra@pesantren.id',
    specialty: 'Tahsin & Matan Jazariyyah',
    totalStudents: 5,
  },
  {
    id: 'tch-3',
    name: 'Ustadz Ridwan Hakim, M.Ag',
    nip: '198511202010011002',
    gender: 'L',
    phone: '0821-4567-8901',
    email: 'ridwan.hakim@pesantren.id',
    specialty: 'Nagham Al-Qur\'an & Murojaah Intensif',
    totalStudents: 3,
  },
];

export const INITIAL_GROUPS: TahfizGroup[] = [
  {
    id: 'grp-1',
    name: 'Halaqah Al-Baqarah (Putra)',
    teacherId: 'tch-1',
    room: 'Masjid Lantai 2 Sayap Timur',
    schedule: 'Ba\'da Shubuh & Ba\'da Ashar (05.30 - 06.30 & 16.00 - 17.15)',
    description: 'Fokus hafalan baru Juz 30, 29, dan Juz 1 lanjutan.',
  },
  {
    id: 'grp-2',
    name: 'Halaqah Maryam (Putri)',
    teacherId: 'tch-2',
    room: 'Gedung Asrama Putri Ruang 102',
    schedule: 'Ba\'da Shubuh & Ba\'da Maghrib (05.30 - 06.30 & 18.30 - 19.30)',
    description: 'Halaqah tahfiz putri akselerasi Juz 30 dan Juz 1.',
  },
  {
    id: 'grp-3',
    name: 'Halaqah An-Nur (Reguler)',
    teacherId: 'tch-3',
    room: 'Perpustakaan Lt. 1',
    schedule: 'Ba\'da Ashar & Ba\'da Isya (16.00 - 17.00 & 20.00 - 21.00)',
    description: 'Fokus pemantapan murojaah dan tahsin makharijul huruf.',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    name: 'Muhammad Farhan',
    nis: '202407001',
    gender: 'L',
    grade: '8A',
    groupId: 'grp-1',
    teacherId: 'tch-1',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 5,
      monthlyRealizationPages: 18,
    },
    totalJuzCompleted: 2,
    totalSurahCompleted: 37,
    totalAyatMemorized: 564,
    currentJuz: 29,
    averageScore: 91,
    joinedDate: '2024-07-15',
  },
  {
    id: 'std-2',
    name: 'Aisyah Humaira',
    nis: '202407002',
    gender: 'P',
    grade: '8B',
    groupId: 'grp-2',
    teacherId: 'tch-2',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 6,
      monthlyTargetPages: 24,
      targetJuzCount: 6,
      monthlyRealizationPages: 22,
    },
    totalJuzCompleted: 3,
    totalSurahCompleted: 42,
    totalAyatMemorized: 710,
    currentJuz: 28,
    averageScore: 94,
    joinedDate: '2024-07-15',
  },
  {
    id: 'std-3',
    name: 'Abdullah Azzam',
    nis: '202407003',
    gender: 'L',
    grade: '7A',
    groupId: 'grp-1',
    teacherId: 'tch-1',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 3,
      monthlyRealizationPages: 16,
    },
    totalJuzCompleted: 1,
    totalSurahCompleted: 28,
    totalAyatMemorized: 395,
    currentJuz: 30,
    averageScore: 86,
    joinedDate: '2024-08-01',
  },
  {
    id: 'std-4',
    name: 'Khadijah Zahra',
    nis: '202407004',
    gender: 'P',
    grade: '7B',
    groupId: 'grp-2',
    teacherId: 'tch-2',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 4,
      monthlyRealizationPages: 19,
    },
    totalJuzCompleted: 1,
    totalSurahCompleted: 37,
    totalAyatMemorized: 564,
    currentJuz: 29,
    averageScore: 89,
    joinedDate: '2024-07-20',
  },
  {
    id: 'std-5',
    name: 'Fatih Al-Ayyubi',
    nis: '202407005',
    gender: 'L',
    grade: '9A',
    groupId: 'grp-1',
    teacherId: 'tch-1',
    status: 'aktif',
    target: {
      dailyTargetPages: 1.5,
      weeklyTargetPages: 7,
      monthlyTargetPages: 28,
      targetJuzCount: 10,
      monthlyRealizationPages: 28,
    },
    totalJuzCompleted: 6,
    totalSurahCompleted: 65,
    totalAyatMemorized: 1420,
    currentJuz: 25,
    averageScore: 96,
    joinedDate: '2023-07-10',
  },
  {
    id: 'std-6',
    name: 'Bilal Habasyi',
    nis: '202407006',
    gender: 'L',
    grade: '8A',
    groupId: 'grp-1',
    teacherId: 'tch-1',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 4,
      monthlyRealizationPages: 12, // Santri yang belum mencapai target (60%)
    },
    totalJuzCompleted: 1,
    totalSurahCompleted: 22,
    totalAyatMemorized: 310,
    currentJuz: 30,
    averageScore: 74,
    joinedDate: '2024-07-15',
  },
  {
    id: 'std-7',
    name: 'Maryam Salimah',
    nis: '202407007',
    gender: 'P',
    grade: '9B',
    groupId: 'grp-2',
    teacherId: 'tch-2',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 7,
      monthlyRealizationPages: 21,
    },
    totalJuzCompleted: 5,
    totalSurahCompleted: 55,
    totalAyatMemorized: 1150,
    currentJuz: 26,
    averageScore: 92,
    joinedDate: '2023-07-10',
  },
  {
    id: 'std-8',
    name: 'Zaid bin Tsabit',
    nis: '202407008',
    gender: 'L',
    grade: '10 IPA 1',
    groupId: 'grp-3',
    teacherId: 'tch-3',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 8,
      monthlyRealizationPages: 20,
    },
    totalJuzCompleted: 7,
    totalSurahCompleted: 70,
    totalAyatMemorized: 1600,
    currentJuz: 8,
    averageScore: 95,
    joinedDate: '2022-07-15',
  },
  {
    id: 'std-9',
    name: 'Ibrahim Khalilullah',
    nis: '202407009',
    gender: 'L',
    grade: '7A',
    groupId: 'grp-3',
    teacherId: 'tch-3',
    status: 'aktif',
    target: {
      dailyTargetPages: 0.5,
      weeklyTargetPages: 3,
      monthlyTargetPages: 12,
      targetJuzCount: 2,
      monthlyRealizationPages: 7, // Belum capai target (58%)
    },
    totalJuzCompleted: 0,
    totalSurahCompleted: 15,
    totalAyatMemorized: 180,
    currentJuz: 30,
    averageScore: 68, // Perlu bimbingan
    joinedDate: '2024-08-10',
  },
  {
    id: 'std-10',
    name: 'Salma Salsabila',
    nis: '202407010',
    gender: 'P',
    grade: '8B',
    groupId: 'grp-2',
    teacherId: 'tch-2',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 5,
      monthlyRealizationPages: 17,
    },
    totalJuzCompleted: 2,
    totalSurahCompleted: 35,
    totalAyatMemorized: 490,
    currentJuz: 29,
    averageScore: 84,
    joinedDate: '2024-07-15',
  },
  {
    id: 'std-11',
    name: 'Hamzah Asadullah',
    nis: '202407011',
    gender: 'L',
    grade: '8A',
    groupId: 'grp-1',
    teacherId: 'tch-1',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 4,
      monthlyRealizationPages: 19,
    },
    totalJuzCompleted: 2,
    totalSurahCompleted: 37,
    totalAyatMemorized: 564,
    currentJuz: 29,
    averageScore: 88,
    joinedDate: '2024-07-15',
  },
  {
    id: 'std-12',
    name: 'Raudhatul Jannah',
    nis: '202407012',
    gender: 'P',
    grade: '7B',
    groupId: 'grp-2',
    teacherId: 'tch-2',
    status: 'aktif',
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 4,
      monthlyTargetPages: 16,
      targetJuzCount: 3,
      monthlyRealizationPages: 15,
    },
    totalJuzCompleted: 1,
    totalSurahCompleted: 30,
    totalAyatMemorized: 420,
    currentJuz: 30,
    averageScore: 87,
    joinedDate: '2024-08-01',
  },
  {
    id: 'std-13',
    name: 'Usman Ghani',
    nis: '202407013',
    gender: 'L',
    grade: '9A',
    groupId: 'grp-3',
    teacherId: 'tch-3',
    status: 'nonaktif', // Nonaktif student demo
    target: {
      dailyTargetPages: 1,
      weeklyTargetPages: 5,
      monthlyTargetPages: 20,
      targetJuzCount: 5,
      monthlyRealizationPages: 0,
    },
    totalJuzCompleted: 2,
    totalSurahCompleted: 37,
    totalAyatMemorized: 564,
    currentJuz: 29,
    averageScore: 82,
    joinedDate: '2023-07-15',
  },
];

const today = new Date().toISOString().split('T')[0];

// Helper to subtract days
function getDateOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

export const INITIAL_RECORDS: MemorizationRecord[] = [
  {
    id: 'rec-1',
    studentId: 'std-1',
    teacherId: 'tch-1',
    date: today,
    type: 'Hafalan Baru',
    juz: 29,
    surahNumber: 67,
    surahName: 'Al-Mulk',
    startAyat: 1,
    endAyat: 15,
    totalAyat: 15,
    assessment: calculateAssessment(92, 90, 88, 95, 95),
    status: 'Lulus',
    notes: 'Makhraj huruf shad dan dhad sudah sangat baik. Dengung ikhfa dijaga 2 harakat.',
    createdAt: `${today}T06:15:00Z`,
  },
  {
    id: 'rec-2',
    studentId: 'std-2',
    teacherId: 'tch-2',
    date: today,
    type: 'Murojaah',
    juz: 30,
    surahNumber: 78,
    surahName: 'An-Naba\'',
    startAyat: 1,
    endAyat: 40,
    totalAyat: 40,
    assessment: calculateAssessment(95, 96, 94, 98, 97),
    status: 'Lulus',
    notes: 'MasyaAllah bacaan sangat tartil, waqaf dan ibtida tepat sekali.',
    createdAt: `${today}T06:25:00Z`,
  },
  {
    id: 'rec-3',
    studentId: 'std-3',
    teacherId: 'tch-1',
    date: today,
    type: 'Hafalan Baru',
    juz: 30,
    surahNumber: 80,
    surahName: '\'Abasa',
    startAyat: 1,
    endAyat: 20,
    totalAyat: 20,
    assessment: calculateAssessment(86, 84, 85, 88, 90),
    status: 'Lulus',
    notes: 'Alhamdulillah lancar. Perhatikan panjang mad thobi\'i pada ayat 15-18.',
    createdAt: `${today}T06:40:00Z`,
  },
  {
    id: 'rec-4',
    studentId: 'std-6',
    teacherId: 'tch-1',
    date: today,
    type: 'Hafalan Baru',
    juz: 30,
    surahNumber: 84,
    surahName: 'Al-Insyiqaq',
    startAyat: 1,
    endAyat: 25,
    totalAyat: 25,
    assessment: calculateAssessment(65, 70, 68, 62, 80),
    status: 'Perlu Mengulang',
    notes: 'Masih sering terhenti pada ayat 10-15. Harap diulang dan disimak teman sebaya sebelum setoran besok.',
    createdAt: `${today}T07:10:00Z`,
  },
  {
    id: 'rec-5',
    studentId: 'std-5',
    teacherId: 'tch-1',
    date: getDateOffset(1),
    type: 'Hafalan Baru',
    juz: 25,
    surahNumber: 43,
    surahName: 'Az-Zukhruf',
    startAyat: 1,
    endAyat: 25,
    totalAyat: 25,
    assessment: calculateAssessment(98, 96, 95, 96, 97),
    status: 'Lulus',
    notes: 'Mumtaz! Hafalan mantap dan tajwid sangat terjaga.',
    createdAt: `${getDateOffset(1)}T16:20:00Z`,
  },
  {
    id: 'rec-6',
    studentId: 'std-4',
    teacherId: 'tch-2',
    date: getDateOffset(1),
    type: 'Murojaah',
    juz: 30,
    surahNumber: 79,
    surahName: 'An-Nazi\'at',
    startAyat: 1,
    endAyat: 46,
    totalAyat: 46,
    assessment: calculateAssessment(88, 88, 87, 90, 92),
    status: 'Lulus',
    notes: 'Kelancaran bagus. Ghunnah musyaddadah ditahan lebih lama sedikit.',
    createdAt: `${getDateOffset(1)}T16:45:00Z`,
  },
  {
    id: 'rec-7',
    studentId: 'std-8',
    teacherId: 'tch-3',
    date: getDateOffset(2),
    type: 'Hafalan Baru',
    juz: 8,
    surahNumber: 6,
    surahName: 'Al-An\'am',
    startAyat: 111,
    endAyat: 125,
    totalAyat: 15,
    assessment: calculateAssessment(95, 94, 95, 96, 95),
    status: 'Lulus',
    notes: 'Alhamdulillah sudah masuk Juz 8 pertengahan. Semangat lanjutkan.',
    createdAt: `${getDateOffset(2)}T16:15:00Z`,
  },
  {
    id: 'rec-8',
    studentId: 'std-9',
    teacherId: 'tch-3',
    date: getDateOffset(2),
    type: 'Hafalan Baru',
    juz: 30,
    surahNumber: 87,
    surahName: 'Al-A\'la',
    startAyat: 1,
    endAyat: 19,
    totalAyat: 19,
    assessment: calculateAssessment(68, 66, 69, 65, 75),
    status: 'Perlu Mengulang',
    notes: 'Huruf \'ain dan dhal masih tertukar. Harap talaqqi ulang bersama ustadz.',
    createdAt: `${getDateOffset(2)}T16:50:00Z`,
  },
  {
    id: 'rec-9',
    studentId: 'std-7',
    teacherId: 'tch-2',
    date: getDateOffset(3),
    type: 'Murojaah',
    juz: 27,
    surahNumber: 55,
    surahName: 'Ar-Rahman',
    startAyat: 1,
    endAyat: 78,
    totalAyat: 78,
    assessment: calculateAssessment(93, 91, 92, 94, 94),
    status: 'Lulus',
    notes: 'Pengulangan fabiayyi aalaa-i robbikumaa tukadzdzibaan sangat fasih.',
    createdAt: `${getDateOffset(3)}T19:00:00Z`,
  },
  {
    id: 'rec-10',
    studentId: 'std-10',
    teacherId: 'tch-2',
    date: getDateOffset(3),
    type: 'Hafalan Baru',
    juz: 29,
    surahNumber: 68,
    surahName: 'Al-Qalam',
    startAyat: 1,
    endAyat: 20,
    totalAyat: 20,
    assessment: calculateAssessment(85, 83, 84, 86, 90),
    status: 'Lulus',
    notes: 'Bagus. Tingkatkan kefasihan pada nun sukun bertemu huruf ikhfa.',
    createdAt: `${getDateOffset(3)}T19:25:00Z`,
  },
  {
    id: 'rec-11',
    studentId: 'std-11',
    teacherId: 'tch-1',
    date: getDateOffset(4),
    type: 'Hafalan Baru',
    juz: 29,
    surahNumber: 67,
    surahName: 'Al-Mulk',
    startAyat: 1,
    endAyat: 30,
    totalAyat: 30,
    assessment: calculateAssessment(89, 87, 86, 90, 92),
    status: 'Lulus',
    notes: 'Surah Al-Mulk tuntas dihafal. Lanjut surah Al-Qalam berikutnya.',
    createdAt: `${getDateOffset(4)}T06:30:00Z`,
  },
  {
    id: 'rec-12',
    studentId: 'std-12',
    teacherId: 'tch-2',
    date: getDateOffset(4),
    type: 'Hafalan Baru',
    juz: 30,
    surahNumber: 82,
    surahName: 'Al-Infitar',
    startAyat: 1,
    endAyat: 19,
    totalAyat: 19,
    assessment: calculateAssessment(88, 86, 85, 89, 90),
    status: 'Lulus',
    notes: 'Alhamdulillah lancar dan tuntas.',
    createdAt: `${getDateOffset(4)}T18:40:00Z`,
  },
  {
    id: 'rec-13',
    studentId: 'std-1',
    teacherId: 'tch-1',
    date: getDateOffset(5),
    type: 'Murojaah',
    juz: 30,
    surahNumber: 81,
    surahName: 'At-Takwir',
    startAyat: 1,
    endAyat: 29,
    totalAyat: 29,
    assessment: calculateAssessment(92, 90, 89, 94, 95),
    status: 'Lulus',
    notes: 'Murojaah mantap dan tidak ada kekeliruan.',
    createdAt: `${getDateOffset(5)}T06:10:00Z`,
  },
  {
    id: 'rec-14',
    studentId: 'std-2',
    teacherId: 'tch-2',
    date: getDateOffset(6),
    type: 'Hafalan Baru',
    juz: 28,
    surahNumber: 58,
    surahName: 'Al-Mujadilah',
    startAyat: 1,
    endAyat: 10,
    totalAyat: 10,
    assessment: calculateAssessment(95, 94, 93, 96, 96),
    status: 'Lulus',
    notes: 'Awal juz 28 dimulai dengan sangat lancar dan fasih.',
    createdAt: `${getDateOffset(6)}T18:30:00Z`,
  },
];

export const APP_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'K.H. Dr. Anwar Musaddad',
    role: 'admin',
    email: 'admin.tahfiz@pesantren.id',
    phone: '0811-2233-4455',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-tch-1',
    name: 'Ustadz Ahmad Zaki, Lc.',
    role: 'teacher',
    email: 'ahmad.zaki@pesantren.id',
    associatedId: 'tch-1',
    phone: '0812-3456-7890',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-tch-2',
    name: 'Ustadzah Fatimah Azzahra, S.Th.I',
    role: 'teacher',
    email: 'fatimah.azzahra@pesantren.id',
    associatedId: 'tch-2',
    phone: '0813-9876-5432',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-std-1',
    name: 'Muhammad Farhan',
    role: 'student',
    email: 'farhan@santri.pesantren.id',
    associatedId: 'std-1',
    phone: '0857-1234-5678',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
];
