import { SurahMeta } from '@/types/tahfiz';

export const ALL_SURAHS: SurahMeta[] = [
  { number: 1, name: 'Al-Fatihah', arabicName: 'الفاتحة', englishTranslation: 'Pembukaan', totalAyah: 7, juz: 1 },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', englishTranslation: 'Sapi Betina', totalAyah: 286, juz: 1 },
  { number: 3, name: 'Ali \'Imran', arabicName: 'آل عمران', englishTranslation: 'Keluarga Imran', totalAyah: 200, juz: 3 },
  { number: 4, name: 'An-Nisa\'', arabicName: 'النساء', englishTranslation: 'Wanita', totalAyah: 176, juz: 4 },
  { number: 5, name: 'Al-Ma\'idah', arabicName: 'المائدة', englishTranslation: 'Hidangan', totalAyah: 120, juz: 6 },
  { number: 6, name: 'Al-An\'am', arabicName: 'الأنعام', englishTranslation: 'Binatang Ternak', totalAyah: 165, juz: 7 },
  { number: 7, name: 'Al-A\'raf', arabicName: 'الأعراف', englishTranslation: 'Tempat Tertinggi', totalAyah: 206, juz: 8 },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', englishTranslation: 'Rampasan Perang', totalAyah: 75, juz: 9 },
  { number: 9, name: 'At-Taubah', arabicName: 'التوبة', englishTranslation: 'Pengampunan', totalAyah: 129, juz: 10 },
  { number: 10, name: 'Yunus', arabicName: 'يونس', englishTranslation: 'Nabi Yunus', totalAyah: 109, juz: 11 },
  { number: 11, name: 'Hud', arabicName: 'هود', englishTranslation: 'Nabi Hud', totalAyah: 123, juz: 11 },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', englishTranslation: 'Nabi Yusuf', totalAyah: 111, juz: 12 },
  { number: 13, name: 'Ar-Ra\'d', arabicName: 'الرعد', englishTranslation: 'Guruh', totalAyah: 43, juz: 13 },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', englishTranslation: 'Nabi Ibrahim', totalAyah: 52, juz: 13 },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', englishTranslation: 'Daerah Bebatuan', totalAyah: 99, juz: 14 },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', englishTranslation: 'Lebah', totalAyah: 128, juz: 14 },
  { number: 17, name: 'Al-Isra\'', arabicName: 'الإسراء', englishTranslation: 'Perjalanan Malam', totalAyah: 111, juz: 15 },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', englishTranslation: 'Gua', totalAyah: 110, juz: 15 },
  { number: 19, name: 'Maryam', arabicName: 'مريم', englishTranslation: 'Siti Maryam', totalAyah: 98, juz: 16 },
  { number: 20, name: 'Taha', arabicName: 'طه', englishTranslation: 'Thaha', totalAyah: 135, juz: 16 },
  { number: 21, name: 'Al-Anbiya\'', arabicName: 'الأنبياء', englishTranslation: 'Para Nabi', totalAyah: 112, juz: 17 },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', englishTranslation: 'Haji', totalAyah: 78, juz: 17 },
  { number: 23, name: 'Al-Mu\'minun', arabicName: 'المؤمنون', englishTranslation: 'Orang Beriman', totalAyah: 118, juz: 18 },
  { number: 24, name: 'An-Nur', arabicName: 'النور', englishTranslation: 'Cahaya', totalAyah: 64, juz: 18 },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', englishTranslation: 'Pembeda', totalAyah: 77, juz: 18 },
  { number: 26, name: 'Asy-Syu\'ara\'', arabicName: 'الشعراء', englishTranslation: 'Penyair', totalAyah: 227, juz: 19 },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', englishTranslation: 'Semut', totalAyah: 93, juz: 19 },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', englishTranslation: 'Kisah-Kisah', totalAyah: 88, juz: 20 },
  { number: 29, name: 'Al-\'Ankabut', arabicName: 'العنكبوت', englishTranslation: 'Laba-laba', totalAyah: 69, juz: 20 },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', englishTranslation: 'Bangsa Romawi', totalAyah: 60, juz: 21 },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', englishTranslation: 'Keluarga Luqman', totalAyah: 34, juz: 21 },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', englishTranslation: 'Sujud', totalAyah: 30, juz: 21 },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', englishTranslation: 'Golongan yang Bersekutu', totalAyah: 73, juz: 21 },
  { number: 34, name: 'Saba\'', arabicName: 'سبإ', englishTranslation: 'Kaum Saba\'', totalAyah: 54, juz: 22 },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', englishTranslation: 'Pencipta', totalAyah: 45, juz: 22 },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', englishTranslation: 'Yaasiin', totalAyah: 83, juz: 22 },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', englishTranslation: 'Barisan-barisan', totalAyah: 182, juz: 23 },
  { number: 38, name: 'Sad', arabicName: 'ص', englishTranslation: 'Shad', totalAyah: 88, juz: 23 },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', englishTranslation: 'Rombongan', totalAyah: 75, juz: 23 },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', englishTranslation: 'Maha Pengampun', totalAyah: 85, juz: 24 },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', englishTranslation: 'Yang Dijelaskan', totalAyah: 54, juz: 24 },
  { number: 42, name: 'Asy-Syura', arabicName: 'الشورى', englishTranslation: 'Musyawarah', totalAyah: 53, juz: 25 },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', englishTranslation: 'Perhiasan', totalAyah: 89, juz: 25 },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', englishTranslation: 'Kabut', totalAyah: 59, juz: 25 },
  { number: 45, name: 'Al-Jasiyah', arabicName: 'الجاثية', englishTranslation: 'Berlutut', totalAyah: 37, juz: 25 },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', englishTranslation: 'Bukit Pasir', totalAyah: 35, juz: 26 },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', englishTranslation: 'Nabi Muhammad', totalAyah: 38, juz: 26 },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', englishTranslation: 'Kemenangan', totalAyah: 29, juz: 26 },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', englishTranslation: 'Kamar-kamar', totalAyah: 18, juz: 26 },
  { number: 50, name: 'Qaf', arabicName: 'ق', englishTranslation: 'Qaaf', totalAyah: 45, juz: 26 },
  { number: 51, name: 'Az-Zariyat', arabicName: 'الذاريات', englishTranslation: 'Angin Menerbangkan', totalAyah: 60, juz: 26 },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', englishTranslation: 'Bukit Tursina', totalAyah: 49, juz: 27 },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', englishTranslation: 'Bintang', totalAyah: 62, juz: 27 },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', englishTranslation: 'Bulan', totalAyah: 55, juz: 27 },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', englishTranslation: 'Maha Pemurah', totalAyah: 78, juz: 27 },
  { number: 56, name: 'Al-Waqi\'ah', arabicName: 'الواقعة', englishTranslation: 'Hari Kiamat', totalAyah: 96, juz: 27 },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', englishTranslation: 'Besi', totalAyah: 29, juz: 27 },
  { number: 58, name: 'Al-Mujadilah', arabicName: 'المجادلة', englishTranslation: 'Gugatan', totalAyah: 22, juz: 28 },
  { number: 59, name: 'Al-Hasyr', arabicName: 'الحشر', englishTranslation: 'Pengusiran', totalAyah: 24, juz: 28 },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', englishTranslation: 'Wanita yang Diuji', totalAyah: 13, juz: 28 },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', englishTranslation: 'Barisan', totalAyah: 14, juz: 28 },
  { number: 62, name: 'Al-Jumu\'ah', arabicName: 'الجمعة', englishTranslation: 'Hari Jum\'at', totalAyah: 11, juz: 28 },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', englishTranslation: 'Orang Munafik', totalAyah: 11, juz: 28 },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', englishTranslation: 'Hari Ditampakkan Kesalahan', totalAyah: 18, juz: 28 },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', englishTranslation: 'Perceraian', totalAyah: 12, juz: 28 },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', englishTranslation: 'Pengharaman', totalAyah: 12, juz: 28 },
  // Juz 29
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', englishTranslation: 'Kerajaan', totalAyah: 30, juz: 29 },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', englishTranslation: 'Pena', totalAyah: 52, juz: 29 },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', englishTranslation: 'Hari Kiamat Nyata', totalAyah: 52, juz: 29 },
  { number: 70, name: 'Al-Ma\'arij', arabicName: 'المعارج', englishTranslation: 'Tempat Naik', totalAyah: 44, juz: 29 },
  { number: 71, name: 'Nuh', arabicName: 'نوح', englishTranslation: 'Nabi Nuh', totalAyah: 28, juz: 29 },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', englishTranslation: 'Jin', totalAyah: 28, juz: 29 },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', englishTranslation: 'Orang Berselimut', totalAyah: 20, juz: 29 },
  { number: 74, name: 'Al-Muddassir', arabicName: 'المدثر', englishTranslation: 'Orang Berkemul', totalAyah: 56, juz: 29 },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', englishTranslation: 'Hari Kebangkitan', totalAyah: 40, juz: 29 },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', englishTranslation: 'Manusia', totalAyah: 31, juz: 29 },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', englishTranslation: 'Malaikat yang Diutus', totalAyah: 50, juz: 29 },
  // Juz 30 (Juz 'Amma)
  { number: 78, name: 'An-Naba\'', arabicName: 'النبإ', englishTranslation: 'Berita Besar', totalAyah: 40, juz: 30 },
  { number: 79, name: 'An-Nazi\'at', arabicName: 'النازعات', englishTranslation: 'Malaikat Pencabut', totalAyah: 46, juz: 30 },
  { number: 80, name: '\'Abasa', arabicName: 'عبس', englishTranslation: 'Bermuka Masam', totalAyah: 42, juz: 30 },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', englishTranslation: 'Menggulung', totalAyah: 29, juz: 30 },
  { number: 82, name: 'Al-Infitar', arabicName: 'الانفطار', englishTranslation: 'Terbelah', totalAyah: 19, juz: 30 },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', englishTranslation: 'Orang yang Curang', totalAyah: 36, juz: 30 },
  { number: 84, name: 'Al-Insyiqaq', arabicName: 'الانشقاق', englishTranslation: 'Terbelah', totalAyah: 25, juz: 30 },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', englishTranslation: 'Gugusan Bintang', totalAyah: 22, juz: 30 },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', englishTranslation: 'Yang Datang di Malam Hari', totalAyah: 17, juz: 30 },
  { number: 87, name: 'Al-A\'la', arabicName: 'الأعلى', englishTranslation: 'Maha Tinggi', totalAyah: 19, juz: 30 },
  { number: 88, name: 'Al-Ghasyiyah', arabicName: 'الغاشية', englishTranslation: 'Hari Pembalasan', totalAyah: 26, juz: 30 },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', englishTranslation: 'Fajar', totalAyah: 30, juz: 30 },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', englishTranslation: 'Negeri', totalAyah: 20, juz: 30 },
  { number: 91, name: 'Asy-Syams', arabicName: 'الشمس', englishTranslation: 'Matahari', totalAyah: 15, juz: 30 },
  { number: 92, name: 'Al-Lail', arabicName: 'الليل', englishTranslation: 'Malam', totalAyah: 21, juz: 30 },
  { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', englishTranslation: 'Waktu Dhuha', totalAyah: 11, juz: 30 },
  { number: 94, name: 'Asy-Syarh', arabicName: 'الشرح', englishTranslation: 'Melapangkan', totalAyah: 8, juz: 30 },
  { number: 95, name: 'At-Tin', arabicName: 'التين', englishTranslation: 'Buah Tin', totalAyah: 8, juz: 30 },
  { number: 96, name: 'Al-\'Alaq', arabicName: 'العلق', englishTranslation: 'Segumpal Darah', totalAyah: 19, juz: 30 },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', englishTranslation: 'Kemuliaan', totalAyah: 5, juz: 30 },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', englishTranslation: 'Bukti Nyata', totalAyah: 8, juz: 30 },
  { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', englishTranslation: 'Kegoncangan', totalAyah: 8, juz: 30 },
  { number: 100, name: 'Al-\'Adiyat', arabicName: 'العاديات', englishTranslation: 'Kuda yang Berlari Kencang', totalAyah: 11, juz: 30 },
  { number: 101, name: 'Al-Qari\'ah', arabicName: 'القارعة', englishTranslation: 'Hari Kiamat', totalAyah: 11, juz: 30 },
  { number: 102, name: 'At-Takasur', arabicName: 'التكاثر', englishTranslation: 'Bermegah-megahan', totalAyah: 8, juz: 30 },
  { number: 103, name: 'Al-\'Asr', arabicName: 'العصر', englishTranslation: 'Masa / Waktu', totalAyah: 3, juz: 30 },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', englishTranslation: 'Pengumpat', totalAyah: 9, juz: 30 },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', englishTranslation: 'Gajah', totalAyah: 5, juz: 30 },
  { number: 106, name: 'Quraisy', arabicName: 'قريش', englishTranslation: 'Suku Quraisy', totalAyah: 4, juz: 30 },
  { number: 107, name: 'Al-Ma\'un', arabicName: 'الماعون', englishTranslation: 'Barang yang Berguna', totalAyah: 7, juz: 30 },
  { number: 108, name: 'Al-Kausar', arabicName: 'الكوثر', englishTranslation: 'Nikmat yang Banyak', totalAyah: 3, juz: 30 },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', englishTranslation: 'Orang-orang Kafir', totalAyah: 6, juz: 30 },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', englishTranslation: 'Pertolongan', totalAyah: 3, juz: 30 },
  { number: 111, name: 'Al-Lahab', arabicName: 'اللهب', englishTranslation: 'Gejolak Api', totalAyah: 5, juz: 30 },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', englishTranslation: 'Kemurnian Keesaan', totalAyah: 4, juz: 30 },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', englishTranslation: 'Waktu Subuh', totalAyah: 5, juz: 30 },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', englishTranslation: 'Manusia', totalAyah: 6, juz: 30 },
];

export const JUZ_LIST = Array.from({ length: 30 }, (_, i) => i + 1);

export function getSurahsByJuz(juzNumber: number): SurahMeta[] {
  if (juzNumber === 30) {
    return ALL_SURAHS.filter((s) => s.number >= 78 && s.number <= 114);
  }
  if (juzNumber === 29) {
    return ALL_SURAHS.filter((s) => s.number >= 67 && s.number <= 77);
  }
  if (juzNumber === 1) {
    return ALL_SURAHS.filter((s) => s.number === 1 || (s.number === 2 && s.totalAyah > 0));
  }
  return ALL_SURAHS.filter((s) => s.juz === juzNumber);
}

export function getSurahByNumber(num: number): SurahMeta | undefined {
  return ALL_SURAHS.find((s) => s.number === num);
}
